
title: Alif Wahid
author:
email:
description: Website

baseurl: ""
url: "https://alifwahid.com"

#twitter_username:
github_username:  alifwahid

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

#disqus:
#  shortname:

#google_analytics:

show_excerpts: true

paginate: 5
paginate_path: "/page:num/"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME

sass:
  style: compressed

header_pages:
  - about.md
