
title: Alif Wahid
author:
email:
description: Personal blog

baseurl: ""
url: "https://www.alifwahid.com"

twitter_username: awah005
github_username:  alifwahid

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

disqus:
  shortname: alifwahid

google_analytics: UA-121681657-1

show_excerpts: true

paginate: 5
paginate_path: "/page:num/"

exclude:
  - README.md

sass:
  style: compressed

header_pages:
  - about.md
